# -*- coding: utf-8 -*-
"""gpt-dev.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/github/Oprixion/myGPT/blob/main/gpt-dev.ipynb
"""

import urllib.request

input_path = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"

with urllib.request.urlopen(input_path) as response:
    text = response.read().decode('utf-8')

print(f"Total characters: {len(text)}")
print(text[:1000])

chars = sorted(list(set(text)))
vocab_size = len(chars)
print("All the unique characters:", ''.join(chars))
print(f"Vocabulary size: {vocab_size}")

# Encoding and decoding functions

stoi = {ch:i for i,ch in enumerate(chars)}
itos = {i:ch for i,ch in enumerate(chars)}

encode = lambda s: [stoi[c] for c in s]
decode = lambda l: ''.join([itos[i] for i in l])

#print(encode("hii there"))
#print(decode(encode("hii there")))

# Creating Tensors
import torch
data = torch.tensor(encode(text), dtype=torch.long)
print(data.shape, data.dtype)
print(data[:1000])

# Train and test splits
n = int(0.9*len(data))
train_data = data[:n]
test_data = data[n:]

context_window = 8
train_data[:context_window+1]

torch.manual_seed(2902)
batch_size = 4 # Number of parallel contexts

# Breaks the data into batches of inputs x and target y
def get_batch(split):
  if split == 'train':
    data = train_data
  elif split == 'test':
    data = test_data
  rand_idx = torch.randint(len(data) - context_window, (batch_size,))
  x = torch.stack([data[i:i + context_window] for i in rand_idx])
  y = torch.stack([data[i+1:i+context_window+1] for i in rand_idx])
  return x,y

xb, yb = get_batch('train')
print('inputs: ')
print(xb.shape)
print(xb)
print("\n")
print("targets: ")
print(yb.shape)
print(yb)

# Bigram language model - Baseline
import torch.nn as nn
from torch.nn import functional as F
torch.manual_seed(2902)

class BigramLanguageModel(nn.Module):
  def __init__(self, vocab_size):
    super().__init__()
    self.token_embedding_table = nn.Embedding(vocab_size, vocab_size)

  def forward(self, idx, targets = None):
    logits = self.token_embedding_table(idx) # (B, T, C)

    if targets == None:
      loss = None
    else:
      # Reshape (B, T, C) to (B, C, T)
      B, T, C = logits.shape
      logits = logits.view(B*T, C)
      targets = targets.view(B*T)
      # Loss function
      loss = F.cross_entropy(logits, targets)

    return logits, loss

  def generate(self, idx, max_new_tokens):
    # idx (B, T) array of indicies og the context
    for _ in range(max_new_tokens):
      # Make predictions
      logits, loss = self(idx)
      # Extract last step
      logits = logits[:, -1, :] # (B, C)
      # Activation (SoftMax)
      probs = F.softmax(logits, dim=-1) # (B, C)
      # Sample the distribution
      idx_next = torch.multinomial(probs, num_samples=1) # (B, 1)
      # Append to sequence
      idx = torch.cat((idx, idx_next), dim=1) # (B, T+1)
    return idx

m = BigramLanguageModel(vocab_size)
logits, loss = m(xb, yb)
print(logits.shape)
print(loss)

# Prediction output
initial_idx = torch.zeros((1,1), dtype=torch.long)
generated_tokens = m.generate(initial_idx, max_new_tokens=100)[0].tolist()
print(decode(generated_tokens))

# Training the BLM

# Create Torch optimizer
optimizer = torch.optim.AdamW(m.parameters(), lr=1e-3)

# Training loop
batch_size = 32 # 32 Parallel sequences
epochs = 10000

for epoch in range(epochs):
  xb, yb = get_batch('train')

  # Evaluate loss
  logits, loss = m(xb, yb)
  optimizer.zero_grad(set_to_none=True)
  loss.backward()
  optimizer.step()

print(loss.item())

# Prediction output
initial_idx = torch.zeros((1,1), dtype=torch.long)
generated_tokens = m.generate(initial_idx, max_new_tokens=100)[0].tolist()
print(decode(generated_tokens))